/*
 * This source file was generated by the Gradle 'init' task
 */
package back.end;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication(scanBasePackages = "back.end")
public class App {

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}
